### ISSUE TITLE
Why use babel with typescript?

### ISSUE THREAD

**Issue by pkieltyka** [damassi/babel-7-typescript-example#1]
Hey guys,

Thanks for the thorough blog post. What I'm trying to understand is: why use babel at all with typescript? the tsc is quite good and will only get better, and Babel 6/7 do not support the full TS language.

**Comment by damassi** [comment]
Hi @pkieltyka - This is a good question! 

The reason is due to existing project infrastructure. If starting a project from scratch we would most certainly stick with `tsc` and go from there, but a lot of our codebases are somewhat old and have complex build pipelines. What Babel 7 + TypeScript support brings to the table is the ability to seamlessly merge old and new tech with very little fuss. For example soon, once Babel 7 stabalizes a bit, we'll be able to set it up in [Positron](https://github.com/artsy/positron) and then import in components from our shared web repo [Reaction](https://github.com/artsy/reaction) directly, rather than having to pre-compile into `dist` and then pull from there. Another side plus is that with `noEmit` set to `false` we can lean on some of the advanced caching options available inside of Babel and Webpack leading to really fast recompiles since all that's happening on the `tsc` side is typechecking.

**Comment by alloy** [comment]
We use some babel plugins that are quite essential to our code-bases, such as the Relay and styled-components ones. This means that we needed to have a pipeline like `tsc` -> `babel` -> `js`. Especially during development this can be quite costly (parse & generate code twice) and can be tedious to setup and maintain.

Even if we’d really wanted to (but I don’t think we’d want to), `tsc` has [no plugin support](https://github.com/Microsoft/TypeScript/issues/16607) at the moment, so being able to build TS code all within Babel is a win in that regard.

Babel indeed doesn’t support namespaces and const enums, but haven’t really had a need for that.

**Comment by pkieltyka** [comment]
Thanks for the reply guys. That makes sense. I am starting a project from scratch and going to use just tsc but I have the feeling eventually I’ll miss out on features Babel has such as tree shaking. I’m pretty sure tsc doesn’t have tree shaking and neither a way to make it work with async module loading for browsers, but I am sure it will support it someday.

Btw, I also use styled components and there is a typescript plugin that works very well with plain tsc.
